### ISSUE TITLE
Issue with Vue 3

### ISSUE THREAD

**Issue by auctumnus** [koca/vue-prism-editor#133]
Tried to use this in a Vue 3 / Vite project, and got this error on build:
```
Pre-bundling dependencies:
  vue
  shiki
  vue-prism-editor
(this will be run only when your dependencies or config have changed)
 > node_modules/.pnpm/vue-prism-editor@1.3.0_vue@3.2.30/node_modules/vue-prism-editor/dist/prismeditor.esm.js:1:7: error: No matching export in "node_modules/.pnpm/vue@3.2.30/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    1 │ import Vue from 'vue';
      ╵        ~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/.pnpm/vue-prism-editor@1.3.0_vue@3.2.30/node_modules/vue-prism-editor/dist/prismeditor.esm.js:1:7: error: No matching export in "node_modules/.pnpm/vue@3.2.30/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    at failureErrorWithLog (/home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1493:15)
    at /home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1149:7)
    at /home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:1258:14
    at /home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/auctumnus/projects/kdl-visualiser/node_modules/.pnpm/esbuild@0.13.15/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```
with `vue-prism-editor@^1.3.0`, `vite@^2.7.2`, `vue@^3.2.25`.

**Comment by auctumnus** [comment]
Never mind, I didn't read the README.
For anyone else hitting this issue, `npm install vue-prism-editor@alpha`.
